### ISSUE TITLE
update mapping format

### ISSUE THREAD

**Issue by aditya17varma** [TanyaaCJain/auto-integrate#30]
Adding more detail to the mapping object returned by the LLMs to make integration easier. Old and new mapping formats are presented below.

Instead of just the field name on the right, we make a dict with 'fields' and 'transform' as keys.
'fields' will be an array, with usually one item. More than one item in the 'fields' array will hint that a transformation is necessary.
'transform' will be a string that tells us if and how to transform the fields:
- 'None': no transform
- 'toInt': cast to int
- 'toBool': cast to boolean
- Similarly for all the other primitive types.
- 'concat': to join two fields (eg. { 'fields': ['first_name', 'last_name'], 'transform': 'concat' } -> first_name + last_name
- 'toArray': return the fields array as is
- 'toObject': cast the items in the 'fields' array as a dictionary / JSON object 

We can add more transforms that are necessary.

new_mapping = {
            "fullName": {'fields': ["name"], 'transform': None},
            "emergencyContactNumber": {'fields': ["emergencyContact"], 'transform': None},
            "DoB": {'fields': ["dateOfBirth"], 'transform': 'ToInt'},
            "city": {'fields': ["city", "state"], 'transform': 'Concat'},
            "honorStudent": {'fields': ["honors"], 'transform': None},
            "state": {'fields': ["state"], 'transform': None},
            "street": {'fields': ["address"], 'transform': None},
            "score": {'fields': ["grade"], 'transform': None},
            "id": {'fields': ["id"], 'transform': None}
        }
    
    old_mapping = {
            "fullName": "name",
            "emergencyContactNumber": "emergencyContact",
            "DoB": "dateOfBirth",
            "city": "city",
            "honorStudent": "honors",
            "state": "state",
            "street": "address",
            "score": "grade",
            "id": "id"
        }

**Comment by TanyaaCJain** [comment]
I like this enhancement to use additional details like 'fields' and 'transform'. Perhaps, we also should think about more complex scenarios such as multiple transformations for a field. 

We should probably provide fallbacks too. For that they may or may not be dependent on conditions.

For example, if a field needs to be concatenated and also be written in a new format.
```json
{
  "transformedField": [
      {
          "transformation": "substring", 
          "source_fields": ["sourceField1"],
          "start": 2, 
          "end": 5,
          "conditions": [
              { 
                  "condition": "length < 2",
                  "fallback": ""
              },
              { 
                  "condition": "2 < length < 5",
                  "fallback": "substring[2:]"
              },
          ]
      },
      {
          "transformation": "concat",
          "source_fields": ["sourceField1", "sourceField2"],
      }
   ]
}
```

In case there is a direct mapping without any transformation, we could do something like:
```json
{
  "transformedField": [
      {
          "transformation": "none", 
          "source_fields": ["sourceField1"]
          "conditions": [
              { 
                  "condition": "none",
                  "fallback": ""
              },
          ]
      }
   ]
}
```

For example, status codes need to be mapped to relevant field values:
```json
{
  "transformedField": [
      {
          "transformation": "mapping", 
          "source_fields": ["statusCode"],
          "conditions": [
              { 
                  "condition": "value == 1",
                  "fallback": "Active"
              },
              { 
                  "condition": "value == 2",
                  "fallback": "Inactive"
              },
              { 
                  "condition": "value == 3",
                  "fallback": "Archived"
              },
          ]
      }
   ]
}
```

**Comment by TanyaaCJain** [comment]
Closing this.
